# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yd3aPt4FN6xaomhy4uRudYdwahvGx28W

# **1..**
"""

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import shap

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import shap

st.set_page_config(page_title="SPICE Solar Revenue Intelligence Dashboard", layout="wide")

st.title("SPICE Solar Revenue Intelligence Dashboard")
st.caption(
    "A tuned Random Forest dashboard for predicting daily solar revenue "
    "and explaining key business drivers."
)

# -----------------------------
# Load files
# -----------------------------
try:
    df = pd.read_csv("combined_dashboard_data.csv")
except Exception as e:
    df = None
    st.error(f"Dataset not found: {e}")

try:
    model = joblib.load("best_rf_model.joblib")
except Exception as e:
    model = None
    st.error(f"Model not found: {e}")

try:
    metrics_df = pd.read_csv("model_metrics.csv")
except Exception as e:
    metrics_df = None
    st.warning(f"Metrics file not found: {e}")

try:
    performance_df = pd.read_csv("performance_data.csv")
except Exception as e:
    performance_df = None
    st.warning(f"Performance data file not found: {e}")

try:
    fi_df = pd.read_csv("feature_importance.csv")
except Exception as e:
    fi_df = None
    st.warning(f"Feature importance file not found: {e}")

try:
    xai_sample_df = pd.read_csv("X_test_sample.csv")
except Exception as e:
    xai_sample_df = None
    st.warning(f"XAI sample data not found: {e}")

# -----------------------------
# Sidebar
# -----------------------------
with st.sidebar:
    st.title("SPICE Dashboard")
    st.markdown("Use the menu below to explore data, predictions, performance, and XAI insights.")
    page = st.radio(
        "Navigation",
        ["Overview", "Data Explorer", "Prediction", "Model Performance", "XAI Insights"]
    )

# -----------------------------
# Overview Page
# -----------------------------
if page == "Overview":
    st.header("Project Overview")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Dataset Rows", len(df) if df is not None else 0)
    col2.metric("Model Features", model.n_features_in_ if model is not None else 0)
    col3.metric("Final Model", "Tuned RF")
    col4.metric("Target", "Daily Revenue")

    st.write("""
    This dashboard predicts daily solar revenue using solar production and AESO market variables.
    It also evaluates model performance and explains which features most influence the prediction.
    """)

    st.divider()

    st.subheader("What you can do in this app")
    st.write("""
    - Explore the dataset
    - Enter values to predict daily revenue
    - Review model performance
    - Understand important drivers through XAI
    """)

    st.divider()

    st.subheader("Key Insights")
    st.write("""
    - Daily revenue depends strongly on both solar output and market price.
    - Lagged and rolling features improve predictive performance.
    - The tuned Random Forest model captures non-linear revenue patterns effectively.
    """)

# -----------------------------
# Data Explorer Page
# -----------------------------
elif page == "Data Explorer":
    st.header("Data Explorer")

    if df is not None:
        col1, col2 = st.columns(2)
        col1.metric("Rows", df.shape[0])
        col2.metric("Columns", df.shape[1])

        st.subheader("Dataset Preview")
        st.dataframe(df.head())

        if st.checkbox("Show full dataset"):
            st.dataframe(df)

        st.divider()

        st.subheader("Column Distribution Explorer")
        selected_col = st.selectbox("Choose a column", df.columns)

        if pd.api.types.is_numeric_dtype(df[selected_col]):
            fig, ax = plt.subplots(figsize=(8, 4))
            ax.hist(df[selected_col].dropna(), bins=20)
            ax.set_title(f"Distribution of {selected_col}")
            ax.set_xlabel(selected_col)
            ax.set_ylabel("Frequency")
            st.pyplot(fig)
            st.caption(f"This histogram shows the distribution of values for {selected_col}.")
        else:
            st.info("Selected column is not numeric, so no histogram is shown.")
    else:
        st.warning("Dataset is not loaded.")

# -----------------------------
# Prediction Page
# -----------------------------
elif page == "Prediction":
    st.header("Revenue Prediction")

    if model is not None:
        feature_columns = list(model.feature_names_in_)
        input_dict = {}

        col1, col2 = st.columns(2)

        for i, col in enumerate(feature_columns):
            default_value = 0.0

            if df is not None and col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
                default_value = float(df[col].median())

            if i % 2 == 0:
                with col1:
                    input_dict[col] = st.number_input(f"{col}", value=default_value)
            else:
                with col2:
                    input_dict[col] = st.number_input(f"{col}", value=default_value)

        if st.button("Predict Revenue"):
            input_df = pd.DataFrame([input_dict])
            prediction = model.predict(input_df)[0]

            st.success(f"Predicted Daily Revenue: ${prediction:,.2f}")
            st.info(
                "This prediction is based on the tuned Random Forest model using "
                "engineered solar and market features."
            )
    else:
        st.warning("Model is not loaded.")

# -----------------------------
# Model Performance Page
# -----------------------------
elif page == "Model Performance":
    st.header("Model Performance")
    st.write("This section shows how well the tuned Random Forest model predicts daily solar revenue.")

    tab1, tab2, tab3 = st.tabs(["Metrics", "Actual vs Predicted", "Residual Analysis"])

    with tab1:
        if metrics_df is not None:
            mae = metrics_df.loc[metrics_df["Metric"] == "MAE", "Value"].values[0]
            rmse = metrics_df.loc[metrics_df["Metric"] == "RMSE", "Value"].values[0]
            mape = metrics_df.loc[metrics_df["Metric"] == "MAPE", "Value"].values[0]

            r2_row = metrics_df.loc[metrics_df["Metric"] == "R2", "Value"]
            r2 = r2_row.values[0] if len(r2_row) > 0 else None

            if r2 is not None:
               col1, col2, col3, col4 = st.columns(4)
               col1.metric("MAE", f"{mae:.4f}")
               col2.metric("RMSE", f"{rmse:.4f}")
               col3.metric("MAPE", f"{mape:.4f}")
               col4.metric("R²", f"{r2:.4f}")

            else:
              col1, col2, col3 = st.columns(3)
              col1.metric("MAE", f"{mae:.4f}")
              col2.metric("RMSE", f"{rmse:.4f}")
              col3.metric("MAPE", f"{mape:.4f}")

    with tab2:
        if performance_df is not None:
            performance_df["Date"] = pd.to_datetime(performance_df["Date"])

            fig1, ax1 = plt.subplots(figsize=(12, 5))
            ax1.plot(performance_df["Date"], performance_df["Actual"], label="Actual")
            ax1.plot(performance_df["Date"], performance_df["Predicted"], label="Predicted")
            ax1.set_title("Actual vs Predicted Daily Revenue")
            ax1.set_xlabel("Date")
            ax1.set_ylabel("Daily Revenue ($)")
            ax1.legend()
            ax1.grid(True)
            st.pyplot(fig1)

            st.caption(
                "This plot compares actual and predicted daily revenue over the test period."
            )
        else:
            st.warning("Performance data is not loaded.")

    with tab3:
        if performance_df is not None:
            performance_df["Residual"] = performance_df["Actual"] - performance_df["Predicted"]

            fig2, ax2 = plt.subplots(figsize=(12, 5))
            ax2.plot(performance_df["Date"], performance_df["Residual"])
            ax2.axhline(0, linestyle="--")
            ax2.set_title("Residuals Over Time")
            ax2.set_xlabel("Date")
            ax2.set_ylabel("Residual (Actual - Predicted)")
            ax2.grid(True)
            st.pyplot(fig2)

            st.caption(
                "Residuals show the difference between actual and predicted values over time."
            )

            st.divider()

            fig3, ax3 = plt.subplots(figsize=(10, 5))
            ax3.hist(performance_df["Residual"], bins=20)
            ax3.set_title("Residual Distribution")
            ax3.set_xlabel("Residual")
            ax3.set_ylabel("Frequency")
            st.pyplot(fig3)

            st.caption(
                "This histogram shows whether prediction errors are centered around zero "
                "or skewed in one direction."
            )
        else:
            st.warning("Performance data is not loaded.")

# -----------------------------
# XAI Insights Page
# -----------------------------
elif page == "XAI Insights":
    st.header("Explainable AI")

    if model is not None and xai_sample_df is not None:
        explainer = shap.Explainer(model, xai_sample_df)
        shap_values = explainer(xai_sample_df)

        st.subheader("SHAP Feature Importance")
        fig_bar = plt.figure()
        shap.summary_plot(shap_values, xai_sample_df, plot_type="bar", show=False)
        st.pyplot(fig_bar)
        plt.clf()

        st.caption(
            "This SHAP bar chart shows which features contribute most strongly to predictions overall."
        )

        st.divider()

        st.subheader("SHAP Summary Plot")
        fig_summary = plt.figure()
        shap.summary_plot(shap_values, xai_sample_df, show=False)
        st.pyplot(fig_summary)
        plt.clf()

        st.caption(
            "This summary plot shows whether high or low feature values push predicted revenue upward or downward."
        )

        st.divider()

        if fi_df is not None:
            top_fi = fi_df.head(10)

            col1, col2 = st.columns([2, 1])

            with col1:
                fig_fi, ax_fi = plt.subplots(figsize=(10, 6))
                ax_fi.barh(top_fi["Feature"], top_fi["Importance"])
                ax_fi.invert_yaxis()
                ax_fi.set_title("Top 10 Random Forest Feature Importances")
                ax_fi.set_xlabel("Importance")
                st.pyplot(fig_fi)

            with col2:
                st.write("""
                **Why this matters**

                These variables have the strongest impact on predicted daily revenue.
                This improves model transparency and supports business interpretation.
                """)
                st.dataframe(top_fi)
        elif hasattr(model, "feature_importances_"):
            fallback_fi = pd.DataFrame({
                "Feature": list(model.feature_names_in_),
                "Importance": model.feature_importances_
            }).sort_values("Importance", ascending=False).head(10)

            fig_fallback, ax_fallback = plt.subplots(figsize=(10, 6))
            ax_fallback.barh(fallback_fi["Feature"], fallback_fi["Importance"])
            ax_fallback.invert_yaxis()
            ax_fallback.set_title("Top 10 Random Forest Feature Importances")
            st.pyplot(fig_fallback)

        st.divider()

        st.subheader("Explain One Prediction")
        selected_index = st.selectbox("Choose a sample row to explain", xai_sample_df.index)

        single_row = xai_sample_df.iloc[[selected_index]]
        single_shap = explainer(single_row)

        fig_waterfall = plt.figure()
        shap.plots.waterfall(single_shap[0], show=False)
        st.pyplot(fig_waterfall)
        plt.clf()

        st.caption(
            "This waterfall plot explains how each feature pushed the selected prediction higher or lower."
        )

    else:
        st.warning("Model or XAI sample data is not loaded.")

st.subheader("Key Insights")
st.write("""
- Daily revenue depends strongly on both solar output and market price.
- Lagged and rolling features improve predictive performance.
- The tuned Random Forest model captures non-linear revenue patterns effectively.
""")